# ===========================================================================
#  GENERATED BY TERRAFORM - do not edit by hand (re-run `terraform apply`).
#  ansible_host = PUBLIC IP (reachable from your Mac, locked to your IP in the
#  security group). The domain still uses the private 10.10.10.0/24 addresses
#  via the group_vars, exactly like the local build.
# ===========================================================================

[domain_controllers]
dc01 ansible_host=${dc01_public_ip}

[domain_members]
${srv01_line}
${ws01_line}

[linux_pivot]
pivot ansible_host=${pivot_public_ip} ansible_connection=ssh ansible_user=ubuntu

[windows:children]
domain_controllers
domain_members

[lab:children]
windows
linux_pivot
